services:
  - type: web
    name: restaurant-pos-deployment
    env: node
    rootDir: restaurant-pos-backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
